jobs:
  build:
    runs-on: "${{ matrix.runs-on }}"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-dotnet@v4"
      with:
        global-json-file: "global.json"
    - run: "dotnet tool restore"
    - run: "dotnet restore"
    - run: "dotnet build --configuration ${{ matrix.configuration }}"
    - run: "dotnet format --verify-no-changes"
    - run: "dotnet test --configuration ${{ matrix.configuration }}"
    - run: "dotnet publish --configuration ${{ matrix.configuration }}"
    - uses: "actions/upload-artifact@v4"
      with:
        name: "${{ matrix.runs-on }}-${{ matrix.configuration }}"
        path: "./src/MeetApp.Backend/bin/${{ matrix.configuration}}/net8.0/publish/"
    strategy:
      matrix:
        configuration: [
          "Debug",
          "Release"
        ]
        runs-on: [
          "macos-latest", 
          "ubuntu-latest", 
          "windows-latest"
        ]
  deploy:
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
    - uses: "actions/download-artifact@v4"
      with:
        name: "ubuntu-latest-Release"
    - uses: "azure/webapps-deploy@v2"
      with:
        app-name: "meet-app-udl"
        #package: "./"
        publish-profile: "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"
name: "main"
on:
  push:
    branches: [ 
      "main" 
    ]
  pull_request:
    branches: [ 
      "main" 
    ]
  schedule:
    - cron: "0 0 * * *"