jobs:
  build:
    runs-on: "${{ matrix.runs-on }}"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-dotnet@v4"
      with:
        global-json-file: "global.json"
    - run: "dotnet tool restore"
    - run: "dotnet restore"
    - run: "dotnet build --configuration ${{ matrix.configuration }}"
    - run: "dotnet format --verify-no-changes"
    - run: "dotnet test --configuration ${{ matrix.configuration }}"
    - uses: "sonarsource/sonarqube-scan-action@3.0.0"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    strategy:
      matrix:
        configuration: [
          "Debug",
          "Release"
        ]
        runs-on: [
          "macos-latest", 
          "ubuntu-latest", 
          "windows-latest"
        ]
name: "main"
on:
  push:
    branches: [ 
      "main" 
    ]
  pull_request:
    branches: [ 
      "main" 
    ]
  schedule:
    - cron: "0 0 * * *"